; PlatformIO Project Configuration File

[env]
platform = espressif8266@^4
framework = arduino
board = nodemcuv2
monitor_speed = 115200
upload_speed = 460800
extra_scripts =
  pre:tools/build_metadata.py
  post:tools/post_upload_sticker.py
custom_fw_version = 0.2.2-alpha
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  bblanchon/ArduinoJson@^7.0.4
  rweather/Crypto@^0.4.0
  knolleary/PubSubClient@^2.8
  paulstoffregen/OneWire@^2.3.8
  milesburton/DallasTemperature@^4.0.5

[env:lrs_za]
build_flags =
  -D REGION_ZA -DLRS_LOG_LEVEL_DEFAULT=3

[env:lrs_us]
build_flags =
  -D REGION_US

[env:lrs_za_ota_rx_v1-1]
extends = env:lrs_za
upload_protocol = espota
upload_port = 192.168.0.131
custom_ota_ip = 192.168.0.131
custom_ota_auth = c48fbb5f
upload_flags =
  --auth=c48fbb5f
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py
  
[env:lrs_za_ota_rx_v1-2]
extends = env:lrs_za
upload_protocol = espota
upload_port = 192.168.0.129
custom_ota_ip = 192.168.0.129
custom_ota_auth = 5fe074a4
upload_flags =
  --auth=5fe074a4
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py

[env:lrs_za_ota_tx]
extends = env:lrs_za
upload_protocol = espota
upload_port = 192.168.0.130
custom_ota_ip = 192.168.0.130
custom_ota_auth =7720c800
upload_flags =
  --auth=7720c800
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py

[env:lrs_za_ota_vic_tx]
extends = env:lrs_za
upload_protocol = espota
upload_port = 192.168.133.110
custom_ota_ip = 192.168.133.110
;custom_ota_auth = admin123
;upload_flags =
;  --auth=admin123
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py

[env:lrs_za_ota_9f_rx]
extends = env:lrs_za
upload_protocol = espota
upload_port = 192.168.0.40
custom_ota_ip = 192.168.0.40
custom_ota_auth = admin123
upload_flags =
  --auth=admin123
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py

[env:lrs_za_ota_9f_tx]
extends = env:lrs_za
upload_protocol = espota
upload_port = 192.168.0.41
custom_ota_ip = 192.168.0.41
custom_ota_auth = admin123
upload_flags =
  --auth=admin123
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py

[env:lrs_us_ota]
extends = env:lrs_us
upload_protocol = espota
upload_port = lrs.local
custom_ota_ip = lrs.local
custom_ota_auth = REPLACE_WITH_US_ADMIN_PASSWORD
extra_scripts =
  pre:tools/build_metadata.py
  pre:tools/force_ota_port.py
  post:tools/post_upload_sticker.py
